name: github.action
channels:
    - https://conda.anaconda.org/conda-forge
    - https://conda.anaconda.org/joshburt
    - https://conda.anaconda.org/ae5-admin
dependencies:
  - anaconda-project
  - conda-build
  - conda-verify
  - setuptools
  - anaconda-client
