[tool.black]
line-length = 120
target-version = ["py311"]


[tool.isort]
line_length = 120
profile = "black"
src_paths = ["workflow", "notebooks"]
known_first_party = ["ae5_tools", "mlflow_adsp"]
skip = ["envs", "data", "user"]
